### ISSUE TITLE
Redirect URI Authentication Issue

### ISSUE THREAD

**Issue by Janzstone** [microsoftgraph/msgraph-sample-uwp#55]
I downloaded the source, renamed the file and added my appid as directed.  When I click Sign In I get:

<img width="490" alt="Snag_4a9670c" src="https://user-images.githubusercontent.com/8989300/231549669-19f6ab40-f98e-44b9-b24c-d1fff56ef739.png">

**Comment by Janzstone** [comment]
I've yet to find a Microsoft.Graph example that did **not** have this issue.

**Comment by jasonjoh** [comment]
Please post a screenshot of the "Authentication" page of your app registration in the Azure portal.
