### ISSUE TITLE
How to obtain email information in the msgraph sample uwp demo? 

### ISSUE THREAD

**Issue by xiakan** [microsoftgraph/msgraph-sample-uwp#58]
How to obtain email information in the msgraph sample uwp demo? I tried to obtain email information and it appears
Code: ErrorAccessDenied
Message: Access is denied. Check credentials and try again.
The code is as follows:
var events = await graphClient.Me.MailFolders["Inbox"].Messages.Request().GetAsync();

**Comment by jasonjoh** [comment]
@xiakan this sample is setup with the appropriate permission scopes to access the user's calendar, not their email.

https://github.com/microsoftgraph/msgraph-sample-uwp/blob/8ee5d4a858d98ac5319f11c327d0cd936f4645a7/GraphTutorial/OAuth.resw.example#L123-L125

To read email, you'd need to add `Mail.Read` (or one of the other possible permission scopes applicable to that API). See [the docs](https://learn.microsoft.com/graph/api/user-list-messages?view=graph-rest-1.0&tabs=http#permissions) for a list of applicable permission scopes.

**Comment by xiakan** [comment]
@jasonjoh Thank you very much!
