### ISSUE TITLE
Missing Type: AttendeePicker

### ISSUE THREAD

**Issue by laultman** [microsoftgraph/msgraph-sample-uwp#60]
**Where did you get the code?**
Downloaded and followed instructions.

**Describe the bug**
Type AttendeePicker is not found.

**To Reproduce**
Follow the instructions for the tutorial.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:  

**Additional context**

**Comment by jasonjoh** [comment]
Possibly a duplicate of #40. Can you try **Clean Solution** and then **Rebuild Solution**?

**Comment by laultman** [comment]
That worked. But found other issues as well #61
