### ISSUE TITLE
Microsoft Graph does not work currently in UWP

### ISSUE THREAD

**Issue by laultman** [microsoftgraph/msgraph-sample-uwp#61]
**Where did you get the code?**
Down load the code

**Describe the bug**
When compiling there are hundreds of errors specifically related to the Microsoft Graph. The current shipping versions have a dependency on .NET 5.0 and will not compile in UWP.

**To Reproduce**
Follow the instructions in the tutorial.

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Dependency versions**
 - Authentication library (MSAL, etc.) version:
 - Graph library (Graph SDK, REST library, etc.) version:  

**Additional context**

**Comment by laultman** [comment]
Update:
Found conflicts between different versions of "System.Security.Principal.Windows" that could not be resolved.
There was a conflict between "System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "System.Security.Principal.Windows, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a".
    "System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was chosen because it was primary and "System.Security.Principal.Windows, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" was not.
    References which depend on "System.Security.Principal.Windows, Version=4.1.1.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" [C:\Users\JLarryAultman\.nuget\packages\microsoft.netcore.universalwindowsplatform\6.2.14\ref\uap10.0.15138\System.Security.Principal.Windows.dll].

**Comment by jasonjoh** [comment]
I do not reproduce this. The project compiles successfully in Visual Studio 2022 version 17.7.7. Can you try **Clean Solution** and then **Rebuild Solution**?

**Comment by laultman** [comment]
You must not be using a current version of Microsoft Graph. [This is not a new issue](https://github.com/dotnet/runtime/issues/62044).

**Comment by jasonjoh** [comment]
This project does not use the Microsoft.Graph library directly, it uses:

```xml
<PackageReference Include="CommunityToolkit.Graph.Uwp">
  <Version>7.1.4</Version>
</PackageReference>
```

https://github.com/microsoftgraph/msgraph-sample-uwp/blob/28904fde179c9872779671dca7ef6d4d29ce727e/GraphTutorial/GraphTutorial.csproj#L178C5-L180C24

I see that they have a dependency on Microsoft.Graph 4.x.

Did you mean to file this report on the [Microsoft.Graph repository](https://github.com/microsoftgraph/msgraph-sdk-dotnet)?

**Comment by laultman** [comment]
No, I was specifically addressing this project. I think it is adequately covered. Nevertheless, MS Graph is pulled in when you restore the nuget packages. I didn't try building it right out of the box, I added my method that referenced the graphclient. Naturally, building it right out of the box is really a useless exercise. You don't even need it to use AAD these days in a UWP for authentication of the local logged in user on a Windows machine.
